services:
  page-docs-postgresql:
    image: bitnami/postgresql:latest
    container_name: page-docs-postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=57893671
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_TIMEZONE=Asia/Shanghai
      - POSTGRESQL_LOG_TIMEZONE=Asia/Shanghai
    volumes:
      - ./postgresql_data:/bitnami/postgresql
    networks:
      - default
    user: root

networks:
  default:
    name: page-docs-network
    driver: bridge
